#pragma config(Sensor, S1,     ultra,               sensorSONAR)
#pragma config(Sensor, S2,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int flag=0;
  while(true)
  {
    if(SensorValue(touch)==1)
    {
      flag=1;
    lable1:  motor[motorB]=70;
      motor[motorC]=70;
      wait1Msec(2000);

    }
    else
   if(SensorValue(ultra)<25)
    {
      motor[motorB]=0;
      motor[motorC]=0;
      wait1Msec(2000);
    }
    else if(flag==1)
      goto lable1;
  }

}
