#pragma config(Sensor, S1,     sonar,               sensorSONAR)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  //nxtDisplayTextLine(3,"Its value is %d",SensorValue(sonar));
 // wait1Msec(3000);
  motor[motorA]=100;

  wait1Msec(150);
}
