#pragma config(Sensor, S1,     pick,                sensorTouch)
#pragma config(Sensor, S2,     back,                sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  int flag=0,counter=0;
  while(true)
  {


    int b=nNxtButtonPressed;
    int count=00;
 loop1:
    switch(b)
    {
      case 1:
      motor[motorA]=-100;
      nxtDisplayBigTextLine(3,"RIGHT");
      wait1Msec(100);
      eraseDisplay();
      motor[motorA]=00;
      break;

      case 2:
      motor[motorA]=100;
      nxtDisplayBigTextLine(3,"LEFT");
      wait1Msec(100);
      eraseDisplay();
      motor[motorA]=00;
      break;

      case 3:
      flag=1;
      motor[motorB]=-100;
      nxtDisplayBigTextLine(3,"UP");
      wait1Msec(100);
      eraseDisplay();
      motor[motorB]=00;
      count+=100;
      break;

   }
   if(SensorValue(back)&& flag==1)
   {
     motor[motorB]=100;
     nxtDisplayBigTextLine(3,"DOWN");
     wait1Msec(count);
     eraseDisplay();
     motor[motorB]=00;
   }
   if(SensorValue(pick))
   {
    if(counter==0)
     {
	    motor[motorC]=-100;
	    wait1Msec(100);
	    motor[motorC]=00;
	    counter=1;
	    continue;
	  }
	  else
    {
      motor[motorC]=100;
	    wait1Msec(100);
	    motor[motorC]=00;
	    counter=0;
	    goto loop1;
    }
  }
}
}
