#pragma config(Sensor, S1,     utlra,               sensorSONAR)
#pragma config(Sensor, S2,     touch,               sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
      loop1:motor[motorB]=75;
      motor[motorC]=75;
      wait1Msec(1000);
      if((SensorValue(touch)==1) || SensorValue(utlra)<30)
      {
          motor[motorB]=-100;
          motor[motorC]=-100;
          wait1Msec(2000);

          motor[motorA]=100;
          wait1Msec(150);
          motor[motorA]=0;

          if(SensorValue(utlra)>30)
          {

            //wait1Msec(3000);
            nxtDisplayTextLine(3,"value is %d",SensorValue(utlra));
            motor[motorA]=-100;
            wait1Msec(120);
            motor[motorA]=0;

            motor[motorB]=-100;
            motor[motorC]=100;
            wait1Msec(300);
            goto loop1;
         }
         else
         {
           motor[motorA]=-100;
           wait1Msec(300);
            motor[motorA]=0;

            if(SensorValue(utlra)>30)
          {
            motor[motorA]=100;
            wait1Msec(150);
             motor[motorA]=0;

            motor[motorB]=100;
            motor[motorC]=-100;
            wait1Msec(300);
            goto loop1;
         }
       }
     }
       else
        goto loop1;
   }
}
