#pragma config(Sensor, S3,     snd,                 sensorSoundDBA)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
      if(SensorValue(snd)<20)
      {
          motor[motorB]=70;
          motor[motorC]=70;
          wait1Msec(2000);
      }
      else
      {
        motor[motorB]=0;
        motor[motorC]=0;
        wait1Msec(2000);
     }
 }
}

