#pragma config(Sensor, S2,     tch,                 sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
  while(true)
  {
   if(SensorValue(tch)==1)
   {
     motor[motorB]=-75;
     motor[motorC]=-75;
     wait1Msec(2000);
     motor[motorB]=-100;
     motor[motorC]=100;
     wait1Msec(300);

  }
  else
  {
    motor[motorB]=75;
    motor[motorC]=75;
  }
 }
}
